#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f sinegen.vcd

#run verilator to translate Verilog into C++, including C++ Testbench
verilator -Wall --cc --trace sinegen.sv --exe sinegen_tb.cpp

#build C++ project via make automatically generated by verilator
make -j -C obj_dir/ -f Vsinegen.mk Vsinegen

#run executable simulation file
obj_dir/Vsinegen